require "modules/hotkey"
require "modules/system"
require "modules/windows"
require "modules/launcher"
require "modules/spoons"
require "modules/timer"
require "modules/jsonFormat"
require "modules/reload"
